import { SortOrder } from "../../util/SortOrder";

export type UserOrderByInput = {
  active?: SortOrder;
  address?: SortOrder;
  addresses?: SortOrder;
  appointmentsTotal?: SortOrder;
  cardId?: SortOrder;
  cash?: SortOrder;
  cheque?: SortOrder;
  city?: SortOrder;
  clientId?: SortOrder;
  cnpj?: SortOrder;
  complement?: SortOrder;
  confirmedEmail?: SortOrder;
  coord?: SortOrder;
  cpf?: SortOrder;
  createdAt?: SortOrder;
  createdById?: SortOrder;
  creditcard?: SortOrder;
  debitcard?: SortOrder;
  distance?: SortOrder;
  email?: SortOrder;
  globalId?: SortOrder;
  id?: SortOrder;
  myOwnerId?: SortOrder;
  name?: SortOrder;
  nextPlan?: SortOrder;
  ownerId?: SortOrder;
  password?: SortOrder;
  payDay?: SortOrder;
  phone?: SortOrder;
  photoId?: SortOrder;
  photoUrl?: SortOrder;
  pix?: SortOrder;
  plan?: SortOrder;
  role?: SortOrder;
  sendedEmail?: SortOrder;
  serviceIds?: SortOrder;
  serviceOptions?: SortOrder;
  transferbank?: SortOrder;
  uf?: SortOrder;
  updatedAt?: SortOrder;
};
