import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";

export type UserWhereInput = {
  active?: BooleanNullableFilter;
  address?: StringNullableFilter;
  addresses?: JsonFilter;
  appointmentsTotal?: IntNullableFilter;
  cardId?: StringNullableFilter;
  cash?: BooleanNullableFilter;
  cheque?: BooleanNullableFilter;
  city?: StringNullableFilter;
  clientId?: StringNullableFilter;
  cnpj?: StringNullableFilter;
  complement?: StringNullableFilter;
  confirmedEmail?: BooleanNullableFilter;
  coord?: JsonFilter;
  cpf?: StringNullableFilter;
  createdById?: StringNullableFilter;
  creditcard?: BooleanNullableFilter;
  debitcard?: BooleanNullableFilter;
  distance?: FloatNullableFilter;
  email?: StringNullableFilter;
  globalId?: StringNullableFilter;
  id?: StringFilter;
  myOwnerId?: StringNullableFilter;
  name?: StringNullableFilter;
  nextPlan?: StringNullableFilter;
  ownerId?: StringNullableFilter;
  password?: StringNullableFilter;
  payDay?: StringNullableFilter;
  phone?: StringNullableFilter;
  photoId?: StringNullableFilter;
  photoUrl?: StringNullableFilter;
  pix?: BooleanNullableFilter;
  plan?: StringNullableFilter;
  role?: StringNullableFilter;
  sendedEmail?: BooleanNullableFilter;
  serviceIds?: StringNullableFilter;
  serviceOptions?: JsonFilter;
  transferbank?: BooleanNullableFilter;
  uf?: StringNullableFilter;
};
