import { InputJsonValue } from "../../types";

export type UserUpdateInput = {
  active?: boolean | null;
  address?: string | null;
  addresses?: InputJsonValue;
  appointmentsTotal?: number | null;
  cardId?: string | null;
  cash?: boolean | null;
  cheque?: boolean | null;
  city?: string | null;
  clientId?: string | null;
  cnpj?: string | null;
  complement?: string | null;
  confirmedEmail?: boolean | null;
  coord?: InputJsonValue;
  cpf?: string | null;
  createdById?: string | null;
  creditcard?: boolean | null;
  debitcard?: boolean | null;
  distance?: number | null;
  email?: string | null;
  globalId?: string | null;
  myOwnerId?: string | null;
  name?: string | null;
  nextPlan?: string | null;
  ownerId?: string | null;
  password?: string | null;
  payDay?: string | null;
  phone?: string | null;
  photoId?: string | null;
  photoUrl?: string | null;
  pix?: boolean | null;
  plan?: string | null;
  role?: string | null;
  sendedEmail?: boolean | null;
  serviceIds?: string | null;
  serviceOptions?: InputJsonValue;
  transferbank?: boolean | null;
  uf?: string | null;
};
