/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Inovacao } from "./Inovacao";
import { InovacaoCountArgs } from "./InovacaoCountArgs";
import { InovacaoFindManyArgs } from "./InovacaoFindManyArgs";
import { InovacaoFindUniqueArgs } from "./InovacaoFindUniqueArgs";
import { DeleteInovacaoArgs } from "./DeleteInovacaoArgs";
import { InovacaoService } from "../inovacao.service";
@graphql.Resolver(() => Inovacao)
export class InovacaoResolverBase {
  constructor(protected readonly service: InovacaoService) {}

  async _inovacaosMeta(
    @graphql.Args() args: InovacaoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Inovacao])
  async inovacaos(
    @graphql.Args() args: InovacaoFindManyArgs
  ): Promise<Inovacao[]> {
    return this.service.inovacaos(args);
  }

  @graphql.Query(() => Inovacao, { nullable: true })
  async inovacao(
    @graphql.Args() args: InovacaoFindUniqueArgs
  ): Promise<Inovacao | null> {
    const result = await this.service.inovacao(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Inovacao)
  async deleteInovacao(
    @graphql.Args() args: DeleteInovacaoArgs
  ): Promise<Inovacao | null> {
    try {
      return await this.service.deleteInovacao(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
