/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Chat as PrismaChat } from "@prisma/client";

export class ChatServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ChatCountArgs, "select">): Promise<number> {
    return this.prisma.chat.count(args);
  }

  async chats<T extends Prisma.ChatFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatFindManyArgs>
  ): Promise<PrismaChat[]> {
    return this.prisma.chat.findMany<Prisma.ChatFindManyArgs>(args);
  }
  async chat<T extends Prisma.ChatFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatFindUniqueArgs>
  ): Promise<PrismaChat | null> {
    return this.prisma.chat.findUnique(args);
  }
  async createChat<T extends Prisma.ChatCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatCreateArgs>
  ): Promise<PrismaChat> {
    return this.prisma.chat.create<T>(args);
  }
  async updateChat<T extends Prisma.ChatUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatUpdateArgs>
  ): Promise<PrismaChat> {
    return this.prisma.chat.update<T>(args);
  }
  async deleteChat<T extends Prisma.ChatDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ChatDeleteArgs>
  ): Promise<PrismaChat> {
    return this.prisma.chat.delete(args);
  }
}
