/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Compliance as PrismaCompliance } from "@prisma/client";

export class ComplianceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ComplianceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.compliance.count(args);
  }

  async compliances<T extends Prisma.ComplianceFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ComplianceFindManyArgs>
  ): Promise<PrismaCompliance[]> {
    return this.prisma.compliance.findMany<Prisma.ComplianceFindManyArgs>(args);
  }
  async compliance<T extends Prisma.ComplianceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ComplianceFindUniqueArgs>
  ): Promise<PrismaCompliance | null> {
    return this.prisma.compliance.findUnique(args);
  }
  async createCompliance<T extends Prisma.ComplianceCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ComplianceCreateArgs>
  ): Promise<PrismaCompliance> {
    return this.prisma.compliance.create<T>(args);
  }
  async updateCompliance<T extends Prisma.ComplianceUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ComplianceUpdateArgs>
  ): Promise<PrismaCompliance> {
    return this.prisma.compliance.update<T>(args);
  }
  async deleteCompliance<T extends Prisma.ComplianceDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ComplianceDeleteArgs>
  ): Promise<PrismaCompliance> {
    return this.prisma.compliance.delete(args);
  }
}
