/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Approval } from "./Approval";
import { ApprovalCountArgs } from "./ApprovalCountArgs";
import { ApprovalFindManyArgs } from "./ApprovalFindManyArgs";
import { ApprovalFindUniqueArgs } from "./ApprovalFindUniqueArgs";
import { DeleteApprovalArgs } from "./DeleteApprovalArgs";
import { ApprovalService } from "../approval.service";
@graphql.Resolver(() => Approval)
export class ApprovalResolverBase {
  constructor(protected readonly service: ApprovalService) {}

  async _approvalsMeta(
    @graphql.Args() args: ApprovalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Approval])
  async approvals(
    @graphql.Args() args: ApprovalFindManyArgs
  ): Promise<Approval[]> {
    return this.service.approvals(args);
  }

  @graphql.Query(() => Approval, { nullable: true })
  async approval(
    @graphql.Args() args: ApprovalFindUniqueArgs
  ): Promise<Approval | null> {
    const result = await this.service.approval(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Approval)
  async deleteApproval(
    @graphql.Args() args: DeleteApprovalArgs
  ): Promise<Approval | null> {
    try {
      return await this.service.deleteApproval(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
