/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MaintenanceService } from "../maintenance.service";
import { MaintenanceCreateInput } from "./MaintenanceCreateInput";
import { Maintenance } from "./Maintenance";
import { MaintenanceFindManyArgs } from "./MaintenanceFindManyArgs";
import { MaintenanceWhereUniqueInput } from "./MaintenanceWhereUniqueInput";
import { MaintenanceUpdateInput } from "./MaintenanceUpdateInput";

export class MaintenanceControllerBase {
  constructor(protected readonly service: MaintenanceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Maintenance })
  async createMaintenance(
    @common.Body() data: MaintenanceCreateInput
  ): Promise<Maintenance> {
    return await this.service.createMaintenance({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Maintenance] })
  @ApiNestedQuery(MaintenanceFindManyArgs)
  async maintenances(@common.Req() request: Request): Promise<Maintenance[]> {
    const args = plainToClass(MaintenanceFindManyArgs, request.query);
    return this.service.maintenances({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Maintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async maintenance(
    @common.Param() params: MaintenanceWhereUniqueInput
  ): Promise<Maintenance | null> {
    const result = await this.service.maintenance({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Maintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMaintenance(
    @common.Param() params: MaintenanceWhereUniqueInput,
    @common.Body() data: MaintenanceUpdateInput
  ): Promise<Maintenance | null> {
    try {
      return await this.service.updateMaintenance({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Maintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMaintenance(
    @common.Param() params: MaintenanceWhereUniqueInput
  ): Promise<Maintenance | null> {
    try {
      return await this.service.deleteMaintenance({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
