/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProviderService } from "../provider.service";
import { ProviderCreateInput } from "./ProviderCreateInput";
import { Provider } from "./Provider";
import { ProviderFindManyArgs } from "./ProviderFindManyArgs";
import { ProviderWhereUniqueInput } from "./ProviderWhereUniqueInput";
import { ProviderUpdateInput } from "./ProviderUpdateInput";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { ReviewWhereUniqueInput } from "../../review/base/ReviewWhereUniqueInput";
import { ServiceBookingFindManyArgs } from "../../serviceBooking/base/ServiceBookingFindManyArgs";
import { ServiceBooking } from "../../serviceBooking/base/ServiceBooking";
import { ServiceBookingWhereUniqueInput } from "../../serviceBooking/base/ServiceBookingWhereUniqueInput";
import { SupportTicketFindManyArgs } from "../../supportTicket/base/SupportTicketFindManyArgs";
import { SupportTicket } from "../../supportTicket/base/SupportTicket";
import { SupportTicketWhereUniqueInput } from "../../supportTicket/base/SupportTicketWhereUniqueInput";

export class ProviderControllerBase {
  constructor(protected readonly service: ProviderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Provider })
  async createProvider(
    @common.Body() data: ProviderCreateInput
  ): Promise<Provider> {
    return await this.service.createProvider({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        profilePicture: true,
        rating: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Provider] })
  @ApiNestedQuery(ProviderFindManyArgs)
  async providers(@common.Req() request: Request): Promise<Provider[]> {
    const args = plainToClass(ProviderFindManyArgs, request.query);
    return this.service.providers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        profilePicture: true,
        rating: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Provider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async provider(
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<Provider | null> {
    const result = await this.service.provider({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        profilePicture: true,
        rating: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Provider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProvider(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() data: ProviderUpdateInput
  ): Promise<Provider | null> {
    try {
      return await this.service.updateProvider({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phoneNumber: true,
          profilePicture: true,
          rating: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Provider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProvider(
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<Provider | null> {
    try {
      return await this.service.deleteProvider({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phoneNumber: true,
          profilePicture: true,
          rating: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/reviews")
  @ApiNestedQuery(ReviewFindManyArgs)
  async findReviews(
    @common.Req() request: Request,
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<Review[]> {
    const query = plainToClass(ReviewFindManyArgs, request.query);
    const results = await this.service.findReviews(params.id, {
      ...query,
      select: {
        comment: true,
        createdAt: true,
        id: true,

        provider: {
          select: {
            id: true,
          },
        },

        rating: true,

        serviceBooking: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/reviews")
  async connectReviews(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        connect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/reviews")
  async updateReviews(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        set: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/reviews")
  async disconnectReviews(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: ReviewWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      reviews: {
        disconnect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/serviceBookings")
  @ApiNestedQuery(ServiceBookingFindManyArgs)
  async findServiceBookings(
    @common.Req() request: Request,
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<ServiceBooking[]> {
    const query = plainToClass(ServiceBookingFindManyArgs, request.query);
    const results = await this.service.findServiceBookings(params.id, {
      ...query,
      select: {
        createdAt: true,
        endTime: true,
        id: true,

        provider: {
          select: {
            id: true,
          },
        },

        requestTime: true,
        serviceType: true,
        startTime: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/serviceBookings")
  async connectServiceBookings(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: ServiceBookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      serviceBookings: {
        connect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/serviceBookings")
  async updateServiceBookings(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: ServiceBookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      serviceBookings: {
        set: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/serviceBookings")
  async disconnectServiceBookings(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: ServiceBookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      serviceBookings: {
        disconnect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/supportTickets")
  @ApiNestedQuery(SupportTicketFindManyArgs)
  async findSupportTickets(
    @common.Req() request: Request,
    @common.Param() params: ProviderWhereUniqueInput
  ): Promise<SupportTicket[]> {
    const query = plainToClass(SupportTicketFindManyArgs, request.query);
    const results = await this.service.findSupportTickets(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        provider: {
          select: {
            id: true,
          },
        },

        status: true,
        subject: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/supportTickets")
  async connectSupportTickets(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: SupportTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supportTickets: {
        connect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/supportTickets")
  async updateSupportTickets(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: SupportTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supportTickets: {
        set: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/supportTickets")
  async disconnectSupportTickets(
    @common.Param() params: ProviderWhereUniqueInput,
    @common.Body() body: SupportTicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supportTickets: {
        disconnect: body,
      },
    };
    await this.service.updateProvider({
      where: params,
      data,
      select: { id: true },
    });
  }
}
