/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FriendService } from "../friend.service";
import { FriendCreateInput } from "./FriendCreateInput";
import { Friend } from "./Friend";
import { Post } from "../../post/base/Post";
import { FriendFindManyArgs } from "./FriendFindManyArgs";
import { FriendWhereUniqueInput } from "./FriendWhereUniqueInput";
import { FriendUpdateInput } from "./FriendUpdateInput";

export class FriendControllerBase {
  constructor(protected readonly service: FriendService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Friend })
  async createFriend(@common.Body() data: FriendCreateInput): Promise<Friend> {
    return await this.service.createFriend({
      data: {
        ...data,

        friend: data.friend
          ? {
              connect: data.friend,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        friend: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Friend] })
  @ApiNestedQuery(FriendFindManyArgs)
  async friends(@common.Req() request: Request): Promise<Friend[]> {
    const args = plainToClass(FriendFindManyArgs, request.query);
    return this.service.friends({
      ...args,
      select: {
        createdAt: true,

        friend: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Friend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async friend(
    @common.Param() params: FriendWhereUniqueInput
  ): Promise<Friend | null> {
    const result = await this.service.friend({
      where: params,
      select: {
        createdAt: true,

        friend: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Friend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFriend(
    @common.Param() params: FriendWhereUniqueInput,
    @common.Body() data: FriendUpdateInput
  ): Promise<Friend | null> {
    try {
      return await this.service.updateFriend({
        where: params,
        data: {
          ...data,

          friend: data.friend
            ? {
                connect: data.friend,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          friend: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Friend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFriend(
    @common.Param() params: FriendWhereUniqueInput
  ): Promise<Friend | null> {
    try {
      return await this.service.deleteFriend({
        where: params,
        select: {
          createdAt: true,

          friend: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/friends")
  @ApiNestedQuery(FriendFindManyArgs)
  async findFriends(
    @common.Req() request: Request,
    @common.Param() params: FriendWhereUniqueInput
  ): Promise<Friend[]> {
    const query = plainToClass(FriendFindManyArgs, request.query);
    const results = await this.service.findFriends(params.id, {
      ...query,
      select: {
        createdAt: true,

        friend: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/friends")
  async connectFriends(
    @common.Param() params: FriendWhereUniqueInput,
    @common.Body() body: FriendWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      friends: {
        connect: body,
      },
    };
    await this.service.updateFriend({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/friends")
  async updateFriends(
    @common.Param() params: FriendWhereUniqueInput,
    @common.Body() body: FriendWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      friends: {
        set: body,
      },
    };
    await this.service.updateFriend({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/friends")
  async disconnectFriends(
    @common.Param() params: FriendWhereUniqueInput,
    @common.Body() body: FriendWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      friends: {
        disconnect: body,
      },
    };
    await this.service.updateFriend({
      where: params,
      data,
      select: { id: true },
    });
  }
}
