export type Order = {
  comissionPaidByOwnerField: boolean | null;
  createdAt: Date;
  id: string;
  orderAppointmentDate: Date | null;
  orderClientId: string | null;
  orderComissionValue: number | null;
  orderCreatedAt: Date | null;
  orderExtraCost: number | null;
  orderHaveFidelity: boolean | null;
  orderNormalCost: number | null;
  orderOwnerId: string | null;
  orderPaidByClientField: boolean | null;
  orderPaymentForm: string | null;
  orderPercentageAdopted: number | null;
  orderPointsUsed: number | null;
  orderProfessionalId: string | null;
  orderRequestId: string | null;
  orderTotalValue: number | null;
  updatedAt: Date;
};
