/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Proposta } from "./Proposta";
import { PropostaCountArgs } from "./PropostaCountArgs";
import { PropostaFindManyArgs } from "./PropostaFindManyArgs";
import { PropostaFindUniqueArgs } from "./PropostaFindUniqueArgs";
import { DeletePropostaArgs } from "./DeletePropostaArgs";
import { PropostaService } from "../proposta.service";
@graphql.Resolver(() => Proposta)
export class PropostaResolverBase {
  constructor(protected readonly service: PropostaService) {}

  async _propostasMeta(
    @graphql.Args() args: PropostaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Proposta])
  async propostas(
    @graphql.Args() args: PropostaFindManyArgs
  ): Promise<Proposta[]> {
    return this.service.propostas(args);
  }

  @graphql.Query(() => Proposta, { nullable: true })
  async proposta(
    @graphql.Args() args: PropostaFindUniqueArgs
  ): Promise<Proposta | null> {
    const result = await this.service.proposta(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Proposta)
  async deleteProposta(
    @graphql.Args() args: DeletePropostaArgs
  ): Promise<Proposta | null> {
    try {
      return await this.service.deleteProposta(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
