/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { CommentUpdateManyWithoutPostsInput } from "./CommentUpdateManyWithoutPostsInput";
import { Type } from "class-transformer";
import { FeedWhereUniqueInput } from "../../feed/base/FeedWhereUniqueInput";
import { LikeUpdateManyWithoutPostsInput } from "./LikeUpdateManyWithoutPostsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class PostUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  author?: string | null;

  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutPostsInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutPostsInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutPostsInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutPostsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeedWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FeedWhereUniqueInput)
  @IsOptional()
  @Field(() => FeedWhereUniqueInput, {
    nullable: true,
  })
  feed?: FeedWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LikeUpdateManyWithoutPostsInput,
  })
  @ValidateNested()
  @Type(() => LikeUpdateManyWithoutPostsInput)
  @IsOptional()
  @Field(() => LikeUpdateManyWithoutPostsInput, {
    nullable: true,
  })
  likes?: LikeUpdateManyWithoutPostsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  media?: InputJsonValue;
}

export { PostUpdateInput as PostUpdateInput };
