/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Innovation } from "./Innovation";
import { InnovationCountArgs } from "./InnovationCountArgs";
import { InnovationFindManyArgs } from "./InnovationFindManyArgs";
import { InnovationFindUniqueArgs } from "./InnovationFindUniqueArgs";
import { DeleteInnovationArgs } from "./DeleteInnovationArgs";
import { InnovationService } from "../innovation.service";
@graphql.Resolver(() => Innovation)
export class InnovationResolverBase {
  constructor(protected readonly service: InnovationService) {}

  async _innovationsMeta(
    @graphql.Args() args: InnovationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Innovation])
  async innovations(
    @graphql.Args() args: InnovationFindManyArgs
  ): Promise<Innovation[]> {
    return this.service.innovations(args);
  }

  @graphql.Query(() => Innovation, { nullable: true })
  async innovation(
    @graphql.Args() args: InnovationFindUniqueArgs
  ): Promise<Innovation | null> {
    const result = await this.service.innovation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Innovation)
  async deleteInnovation(
    @graphql.Args() args: DeleteInnovationArgs
  ): Promise<Innovation | null> {
    try {
      return await this.service.deleteInnovation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
