/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Following as PrismaFollowing } from "@prisma/client";

export class FollowingServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FollowingCountArgs, "select">
  ): Promise<number> {
    return this.prisma.following.count(args);
  }

  async followings<T extends Prisma.FollowingFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FollowingFindManyArgs>
  ): Promise<PrismaFollowing[]> {
    return this.prisma.following.findMany<Prisma.FollowingFindManyArgs>(args);
  }
  async following<T extends Prisma.FollowingFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FollowingFindUniqueArgs>
  ): Promise<PrismaFollowing | null> {
    return this.prisma.following.findUnique(args);
  }
  async createFollowing<T extends Prisma.FollowingCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FollowingCreateArgs>
  ): Promise<PrismaFollowing> {
    return this.prisma.following.create<T>(args);
  }
  async updateFollowing<T extends Prisma.FollowingUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.FollowingUpdateArgs>
  ): Promise<PrismaFollowing> {
    return this.prisma.following.update<T>(args);
  }
  async deleteFollowing<T extends Prisma.FollowingDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.FollowingDeleteArgs>
  ): Promise<PrismaFollowing> {
    return this.prisma.following.delete(args);
  }

  async findFollowings(
    parentId: string,
    args: Prisma.FollowingFindManyArgs
  ): Promise<PrismaFollowing[]> {
    return this.prisma.following
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .followings(args);
  }

  async getFollowing(parentId: string): Promise<PrismaFollowing | null> {
    return this.prisma.following
      .findUnique({
        where: { id: parentId },
      })
      .following();
  }
}
