/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Contato } from "./Contato";
import { ContatoCountArgs } from "./ContatoCountArgs";
import { ContatoFindManyArgs } from "./ContatoFindManyArgs";
import { ContatoFindUniqueArgs } from "./ContatoFindUniqueArgs";
import { DeleteContatoArgs } from "./DeleteContatoArgs";
import { ContatoService } from "../contato.service";
@graphql.Resolver(() => Contato)
export class ContatoResolverBase {
  constructor(protected readonly service: ContatoService) {}

  async _contatoesMeta(
    @graphql.Args() args: ContatoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Contato])
  async contatoes(
    @graphql.Args() args: ContatoFindManyArgs
  ): Promise<Contato[]> {
    return this.service.contatoes(args);
  }

  @graphql.Query(() => Contato, { nullable: true })
  async contato(
    @graphql.Args() args: ContatoFindUniqueArgs
  ): Promise<Contato | null> {
    const result = await this.service.contato(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Contato)
  async deleteContato(
    @graphql.Args() args: DeleteContatoArgs
  ): Promise<Contato | null> {
    try {
      return await this.service.deleteContato(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
