/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Aprovacao } from "./Aprovacao";
import { AprovacaoCountArgs } from "./AprovacaoCountArgs";
import { AprovacaoFindManyArgs } from "./AprovacaoFindManyArgs";
import { AprovacaoFindUniqueArgs } from "./AprovacaoFindUniqueArgs";
import { DeleteAprovacaoArgs } from "./DeleteAprovacaoArgs";
import { AprovacaoService } from "../aprovacao.service";
@graphql.Resolver(() => Aprovacao)
export class AprovacaoResolverBase {
  constructor(protected readonly service: AprovacaoService) {}

  async _aprovacaosMeta(
    @graphql.Args() args: AprovacaoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Aprovacao])
  async aprovacaos(
    @graphql.Args() args: AprovacaoFindManyArgs
  ): Promise<Aprovacao[]> {
    return this.service.aprovacaos(args);
  }

  @graphql.Query(() => Aprovacao, { nullable: true })
  async aprovacao(
    @graphql.Args() args: AprovacaoFindUniqueArgs
  ): Promise<Aprovacao | null> {
    const result = await this.service.aprovacao(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Aprovacao)
  async deleteAprovacao(
    @graphql.Args() args: DeleteAprovacaoArgs
  ): Promise<Aprovacao | null> {
    try {
      return await this.service.deleteAprovacao(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
