/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Usuario } from "./Usuario";
import { UsuarioCountArgs } from "./UsuarioCountArgs";
import { UsuarioFindManyArgs } from "./UsuarioFindManyArgs";
import { UsuarioFindUniqueArgs } from "./UsuarioFindUniqueArgs";
import { DeleteUsuarioArgs } from "./DeleteUsuarioArgs";
import { UsuarioService } from "../usuario.service";
@graphql.Resolver(() => Usuario)
export class UsuarioResolverBase {
  constructor(protected readonly service: UsuarioService) {}

  async _usuariosMeta(
    @graphql.Args() args: UsuarioCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Usuario])
  async usuarios(
    @graphql.Args() args: UsuarioFindManyArgs
  ): Promise<Usuario[]> {
    return this.service.usuarios(args);
  }

  @graphql.Query(() => Usuario, { nullable: true })
  async usuario(
    @graphql.Args() args: UsuarioFindUniqueArgs
  ): Promise<Usuario | null> {
    const result = await this.service.usuario(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Usuario)
  async deleteUsuario(
    @graphql.Args() args: DeleteUsuarioArgs
  ): Promise<Usuario | null> {
    try {
      return await this.service.deleteUsuario(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
