/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CampanhaMarketing } from "./CampanhaMarketing";
import { CampanhaMarketingCountArgs } from "./CampanhaMarketingCountArgs";
import { CampanhaMarketingFindManyArgs } from "./CampanhaMarketingFindManyArgs";
import { CampanhaMarketingFindUniqueArgs } from "./CampanhaMarketingFindUniqueArgs";
import { DeleteCampanhaMarketingArgs } from "./DeleteCampanhaMarketingArgs";
import { CampanhaMarketingService } from "../campanhaMarketing.service";
@graphql.Resolver(() => CampanhaMarketing)
export class CampanhaMarketingResolverBase {
  constructor(protected readonly service: CampanhaMarketingService) {}

  async _campanhaMarketingsMeta(
    @graphql.Args() args: CampanhaMarketingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CampanhaMarketing])
  async campanhaMarketings(
    @graphql.Args() args: CampanhaMarketingFindManyArgs
  ): Promise<CampanhaMarketing[]> {
    return this.service.campanhaMarketings(args);
  }

  @graphql.Query(() => CampanhaMarketing, { nullable: true })
  async campanhaMarketing(
    @graphql.Args() args: CampanhaMarketingFindUniqueArgs
  ): Promise<CampanhaMarketing | null> {
    const result = await this.service.campanhaMarketing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CampanhaMarketing)
  async deleteCampanhaMarketing(
    @graphql.Args() args: DeleteCampanhaMarketingArgs
  ): Promise<CampanhaMarketing | null> {
    try {
      return await this.service.deleteCampanhaMarketing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
